LABEL_BOOST = {
    "Agricultural Equipment Services": ["agricultural", "farm", "equipment", "machinery"],
    "Soil Nutrient Application Services": ["soil", "nutrient", "fertilizer", "compost", "land improvement"],
    "Pesticide Application Services": ["pesticide", "herbicide", "insecticide", "spraying"],
    "Ornamental Plant Nurseries": ["ornamental plants", "nursery", "horticulture", "garden center"],
    "Landscaping Services": ["landscaping", "landscape", "yard", "lawn", "garden"],
    "Gardening Services": ["gardening", "flowers", "plants", "weeding"],
    "Tree Services - Pruning / Removal": ["tree services", "pruning", "tree removal", "arborist"],
    "Veterinary Services": ["veterinary", "vet", "animal health"],
    "Veterinary Clinics": ["vet clinic", "animal hospital", "veterinary center"],
    "Pet Boarding Services": ["pet boarding", "kennel", "pet hotel"],
    "Animal Day Care Services": ["animal daycare", "pet day care", "petsit"],
    "Pet Grooming Services": ["pet grooming", "dog grooming", "cat grooming", "pet spa"],
    "Animal Training Services": ["animal training", "obedience", "behavior modification"],
    "Veterinary Health Centers": ["vet health", "veterinary center", "animal wellness"],
    "Animal Trainers": ["animal trainer", "dog trainer", "horse trainer", "obedience"],
    "Livestock Dealer Services": ["livestock", "cattle", "poultry", "agriculture"],
    "Timber Harvesting Operations": ["timber", "logging", "forest", "wood harvest"],
    "Fishing and Hunting Services": ["fishing", "hunting", "angling", "wildlife"],
    "Well Maintenance Services": ["well maintenance", "water well", "pump servicing"],
    "Field Welding Services": ["field welding", "portable welder", "metal join"],
    "Sand and Gravel Mining": ["sand mining", "gravel mining", "quarry", "aggregate"],
    "Residential Driveway Construction": ["residential driveway", "concrete driveway", "asphalt driveway"],
    "Commercial Driveway Construction": ["commercial driveway", "parking lot", "paving"],
    "Fencing Construction Services": ["fencing", "fence build", "wood fence", "metal fence"],
    "Sidewalk Construction Services": ["sidewalk construction", "pavement", "concrete walk"],
    "Commercial Irrigation Systems": ["commercial irrigation", "sprinkler", "watering system"],
    "Residential Drainage Systems": ["residential drainage", "storm drain", "french drain"],
    "Residential Snow Removal": ["residential snow removal", "plowing", "shoveling"],
    "Commercial Snow Removal": ["commercial snow removal", "snow hauling", "plowing"],
    "General Snow Removal Services": ["snow removal", "de-icing", "winter maintenance"],
    "Land Leveling Services": ["land leveling", "grading", "earth moving"],
    "Residential Drain Cleaning": ["residential drain", "plumbing", "clog removal"],
    "Commercial Drain Cleaning": ["commercial drain", "plumbing", "clog removal"],
    "Street Cleaning Operations": ["street cleaning", "road sweeping", "municipal cleaning"],
    "Conveyor System Installation": ["conveyor system", "belt conveyor", "roller conveyor"],
    "Low-Rise Signage Installation": ["low-rise signage", "sign install", "billboard"],
    "High-Rise Signage Installation": ["high-rise signage", "sign skyscraper", "large signage"],
    "Tank Installation Services": ["tank installation", "storage tank", "fuel tank"],
    "Residential Communication Equipment Installation": ["residential communication", "cable install", "internet install"],
    "Commercial Communication Equipment Installation": ["commercial communication", "network install", "telecom wiring"],
    "Low-Rise Glass Installation": ["low-rise glass", "window install", "storefront glass"],
    "High-Rise Glass Installation": ["high-rise glass", "curtain wall", "skyscraper glazing"],
    "Industrial Machinery Installation": ["industrial machinery install", "factory equipment", "heavy machinery"],
    "Agricultural Machinery Installation": ["agricultural machinery", "farm equipment install", "harvester"],
    "Grain Handling Machinery Installation": ["grain handling", "silo", "grain elevator", "conveyor"],
    "Dock and Pier Construction": ["dock construction", "pier", "marina", "waterfront"],
    "Road and Highway Construction": ["road construction", "highway building", "paving", "asphalt"],
    "Road Maintenance Services": ["road maintenance", "pothole repair", "line painting"],
    "Pipeline Construction Services": ["pipeline construction", "oil pipeline", "gas pipeline", "welding"],
    "New Ground Pipeline Installation": ["new pipeline", "trench pipeline", "utility install"],
    "Excavation Services": ["excavation", "earthworks", "digging", "site grading"],
    "Residential Plumbing Services": ["residential plumbing", "home pipes", "fixtures", "plumber"],
    "Commercial Plumbing Services": ["commercial plumbing", "industrial plumber", "building piping"],
    "Industrial Plumbing Services": ["industrial plumbing", "large scale piping", "processing plant piping"],
    "Boiler Installation Services": ["boiler install", "hvac", "heating system"],
    "Boiler Repair Services": ["boiler repair", "furnace fix", "heating system fix"],
    "Steam Services": ["steam system", "steam boiler", "steam piping"],
    "Gas Installation Services": ["gas install", "gas piping", "natural gas", "propane"],
    "Medical Gas Installation Services": ["medical gas", "hospital piping", "oxygen lines"],
    "Fire Protection System Services": ["fire protection", "sprinkler system", "fire alarm"],
    "HVAC Installation and Service": ["hvac", "heating", "ventilation", "air conditioning"],
    "HVAC Inspections": ["hvac inspections", "system check", "air quality"],
    "Air Duct Cleaning Services": ["air duct cleaning", "vent cleaning", "indoor air", "hvac cleaning"],
    "Water Treatment Services": ["water treatment", "filtration", "purification", "softening"],
    "Residential Electrical Services": ["residential electrical", "home wiring", "breaker panel"],
    "Commercial Electrical Services": ["commercial electrical", "3-phase power", "industrial wiring"],
    "Alarm Installation Services": ["alarm install", "security alarm", "fire alarm"],
    "Electric Line Construction": ["electric line", "power line", "distribution line"],
    "Cable Installation Services": ["cable install", "coax", "fiber optic", "structured cabling"],
    "Elevator Installation Services": ["elevator install", "lift", "escalator"],
    "Low-Rise Foundation Construction": ["foundation construction", "basement", "footing"],
    "High-Rise Foundation Construction": ["high-rise foundation", "deep foundation", "pile"],
    "Precast Concrete Installation": ["precast concrete", "modular concrete", "panel install"],
    "Tilt-Up Concrete Services": ["tilt-up concrete", "wall panels", "concrete tilt"],
    "Masonry Construction Services": ["masonry", "bricklaying", "stonework"],
    "Drywall Services": ["drywall", "sheetrock", "gypsum board"],
    "Tile Installation Services": ["tile install", "ceramic tile", "porcelain tile"],
    "Carpentry Services": ["carpentry", "woodwork", "framing", "joinery"],
    "Millwork Services": ["millwork", "custom wood", "cabinetry", "trim"],
    "General Handyman Services": ["handyman", "repairs", "small tasks", "odd jobs"],
    "Insulation Services": ["insulation", "thermal", "soundproofing", "spray foam"],
    "Painting Services": ["painting", "interior paint", "exterior paint", "brush", "roller"],
    "Spray Painting Services": ["spray painting", "spray gun", "lacquer", "automotive painting"],
    "Flooring Installation Services": ["flooring", "hardwood", "laminate", "tile flooring"],
    "Interior Design Services": ["interior design", "decor", "furniture layout", "color scheme"],
    "Home Staging Services": ["home staging", "real estate staging", "property styling"],
    "Sheet Metal Services": ["sheet metal", "fabrication", "ductwork", "metal cutting"],
    "Welding Services": ["welding", "metal join", "tig welding", "mig welding"],
    "Structural Steel Erection": ["structural steel", "steel beams", "frame building"],
    "Non-Structural Steel Fabrication": ["non-structural steel", "ornamental steel", "handrails"],
    "Windows and Doors Installation": ["window install", "door install", "frames", "glazing"],
    "Well Drilling Services": ["well drilling", "borehole", "water well"],
    "Directional Drilling Services": ["directional drilling", "horizontal drilling", "trenchless"],
    "Infrastructure Excavation": ["infrastructure excavation", "civils", "deep dig", "utility trench"],
    "New Ground Excavation": ["new ground excavation", "site prep", "foundation dig"],
    "Residential Roofing Services": ["residential roofing", "shingles", "roof repair"],
    "Roofing Services with Heat Application": ["torch on roofing", "hot roofing", "bitumen roof"],
    "Waterproofing Services": ["waterproofing", "membrane", "sealant", "water barrier"],
    "Septic System Services": ["septic system", "septic tank", "drain field"],
    "Building Cleaning Services": ["building cleaning", "janitorial", "custodial", "commercial cleaning"],
    "Fire Safety Equipment Services": ["fire safety", "extinguishers", "sprinklers", "alarms"],
    "Testing and Inspection Services": ["testing", "inspection", "compliance check", "quality control"],
    "Single Family Residential Construction": ["single family construction", "house building"],
    "Single Family Renovation Services": ["single family renovation", "remodel", "house refurbishment"],
    "Multi-Family Construction Services": ["multi-family building", "apartment construction", "condo building"],
    "Apartment Renovation Services": ["apartment renovation", "rehab", "remodel", "flats improvement"],
    "Restoration Services": ["restoration", "fire damage", "water damage", "historical building"],
    "Mobile Home Construction Services": ["mobile home", "manufactured home", "prefab home"],
    "Commercial Construction Services": ["commercial construction", "office building", "retail build"],
    "Commercial Renovation Services": ["commercial renovation", "office remodel", "tenant improvement"],
    "Swimming Pool Installation Services": ["pool install", "in-ground pool", "above-ground pool"],
    "Swimming Pool Maintenance Services": ["pool maintenance", "pool cleaning", "chemical balancing"],
    "Vacant Building Management": ["vacant building", "property mgmt", "security checks"],
    "Vacant Land Services": ["vacant land", "land mgmt", "land clearing"],
    "Meat Processing Services": ["meat processing", "slaughterhouse", "butchering", "packaging"],
    "Seafood Processing Services": ["seafood processing", "fish processing", "canning", "freezing"],
    "Dairy Production Services": ["dairy production", "milk processing", "cheese", "pasteurization"],
    "Frozen Food Processing": ["frozen food", "freezing", "packaging", "cold chain"],
    "Ice Production Services": ["ice production", "ice factory", "block ice", "crushed ice"],
    "Canning Services": ["canning", "tin can", "food preservation"],
    "Animal Feed Manufacturing": ["animal feed", "fodder", "grain feed", "pellets"],
    "Pet Food Manufacturing": ["pet food", "kibble", "dog food", "cat food"],
    "Grain Processing Services": ["grain processing", "milling", "flour", "cereal"],
    "Coffee Processing Services": ["coffee processing", "beans roasting", "grinding"],
    "Seed Processing Services": ["seed processing", "cleaning seeds", "seed packaging"],
    "Bakery Production Services": ["bakery production", "bread", "pastry", "baking"],
    "Confectionery Manufacturing": ["confectionery", "candy", "chocolate", "sweets"],
    "Distilling Services": ["distilling", "liquor", "alcohol production", "spirits"],
    "Brewery Operations": ["brewery", "beer", "microbrewery", "malt"],
    "Non-Alcoholic Beverage Manufacturing": ["beverage", "soft drinks", "juice", "soda"],
    "Oil and Fat Manufacturing": ["oil manufacturing", "fat processing", "edible oils", "shortening"],
    "Rendering Services": ["rendering", "animal byproducts", "tallow", "bone meal"],
    "Textile Manufacturing Services": ["textile", "fabric", "yarn", "weaving", "knitting"],
    "Carpet Manufacturing Services": ["carpet manufacturing", "loom", "rug making"],
    "Apparel Manufacturing": ["apparel", "clothing", "garments", "fashion"],
    "Accessory Manufacturing": ["accessories", "bags", "belts", "scarves"],
    "Children's Clothing Manufacturing": ["children's clothing", "kids wear", "baby clothes"],
    "Window Treatment Manufacturing": ["window treatment", "curtains", "blinds", "shades"],
    "Canvas Manufacturing": ["canvas", "tarpaulins", "heavy fabric"],
    "Rope Production Services": ["rope production", "twine", "cord", "braiding"],
    "Tent Manufacturing Services": ["tent manufacturing", "camping", "canvas", "fabrication"],
    "Wood Product Manufacturing": ["wood product", "lumber", "millwork", "joinery"],
    "Window and Door Manufacturing": ["window manufacturing", "door manufacturing", "frames"],
    "Cabinetry Manufacturing": ["cabinetry", "kitchen cabinets", "wood shops"],
    "Trim Manufacturing": ["trim", "mouldings", "wood finishing"],
    "Pallet Manufacturing": ["pallet", "wood packaging", "shipping pallet"],
    "Furniture Manufacturing": ["furniture", "sofa", "table", "chair", "carpentry"],
    "Bedding Manufacturing": ["bedding", "mattress", "pillows", "quilts"],
    "Paper Production Services": ["paper production", "pulp", "paper mill"],
    "Stationery Manufacturing": ["stationery", "envelopes", "notebooks", "paper goods"],
    "Publishing Services": ["publishing", "books", "magazines", "editing"],
    "Printing Services": ["printing", "offset print", "digital print", "press"],
    "Gas Manufacturing Services": ["gas manufacturing", "industrial gas", "oxygen", "nitrogen"],
    "Ink Production Services": ["ink production", "pigments", "printing ink"],
    "Plastic Manufacturing": ["plastic manufacturing", "injection molding", "extrusion", "resins"],
    "Cosmetic Manufacturing": ["cosmetic", "makeup", "skincare", "beauty products"],
    "Soap Production Services": ["soap production", "saponification", "detergent"],
    "Chemical Manufacturing": ["chemical manufacturing", "reactors", "acids", "alkalis", "solvents"],
    "Asphalt Production Services": ["asphalt production", "bitumen", "paving mix"],
    "Rubber Manufacturing": ["rubber", "latex", "vulcanization", "tires"],
    "Plastic Signage Production": ["plastic signage", "sign boards", "display boards"],
    "Media Production Services": ["media production", "video", "film", "audio", "broadcast"],
    "Software Manufacturing": ["software dev", "packaged software", "cd pressing", "disks"],
    "Food Processing Services": ["food processing", "packaging", "preservation"],
    "Pharmaceutical Manufacturing": ["pharmaceutical", "drugs", "medicine", "lab", "formulation"],
    "Laboratory Services": ["lab services", "testing lab", "analysis", "samples"],
    "Waste Management Services": ["waste mgmt", "garbage disposal", "refuse", "landfill"],
    "Recycling Services": ["recycling", "materials recovery", "plastics recycling"],
    "Environmental Consulting": ["environmental consulting", "ecology", "pollution", "sustainability"],
    "Property Management Services": ["property mgmt", "landlord", "tenant", "leasing"],
    "Real Estate Services": ["real estate", "broker", "realtor", "housing", "mortgage", "lease"],
    "Insurance Services": ["insurance", "policy", "coverage", "risk", "claims", "underwriting"],
    "Financial Services": ["finance", "banking", "investment", "loan", "money"],
    "Legal Services": ["legal", "law", "attorney", "court", "litigation", "contracts"],
    "Consulting Services": ["consulting", "advisory", "expert advice", "professional services"],
    "Marketing Services": ["marketing", "advertising", "branding", "promotion", "campaign"],
    "Human Resources Services": ["hr", "recruitment", "talent", "staffing", "personnel", "onboarding"],
    "Management Consulting": ["management consulting", "strategy", "process improvement", "organizational dev"],
    "Business Development Services": ["business development", "partnerships", "growth strategy", "client expansion"],
    "Project Management Services": ["project mgmt", "pm", "planning", "scheduling", "gantt"],
    "Technology Consulting": ["technology", "it systems", "digital transformation", "software", "hardware"],
    "Software Development Services": ["software dev", "apps", "programming", "coding", "devops"],
    "Data Analysis Services": ["data analysis", "analytics", "insights", "stats", "machine learning"],
    "Market Research Services": ["market research", "consumer insights", "survey", "focus group"],
    "Strategic Planning Services": ["strategic planning", "long term strategy", "mission", "vision"],
    "Training Services": ["training", "coaching", "workshops", "seminars", "tutorials"],
    "Public Relations Services": ["public relations", "pr", "press release", "media coverage", "outreach"],
    "Event Planning Services": ["event planning", "conferences", "trade shows", "expositions"],
    "Catering Services": ["catering", "food services", "banquet", "meal supply"],
    "Travel Services": ["travel", "tourism", "vacation", "reservations"],
    "Digital Marketing Services": ["digital marketing", "seo", "ppc", "online ads", "social media marketing"],
    "E-Commerce Services": ["ecommerce", "online store", "checkout", "payment gateway", "shopify"],
    "Online Marketing Services": ["online marketing", "web campaigns", "digital ads", "banner ads"],
    "Content Creation Services": ["content creation", "copywriting", "video production", "blogging"],
    "Website Development Services": ["web dev", "frontend", "backend", "ui/ux", "cms"],
    "SEO Services": ["seo", "search engine optimization", "google ranking", "keywords"],
    "Social Media Services": ["social media", "facebook", "instagram", "twitter", "influencer"],
    "Branding Services": ["branding", "brand identity", "logo", "visual identity", "brand strategy"],
    "Graphic Design Services": ["graphic design", "layout", "typography", "illustration"],
    "Advertising Services": ["advertising", "ad creative", "media buy", "billboards", "copywriting"],
    "Corporate Training Services": ["corporate training", "employee development", "skill building", "workshops"],
    "Health and Safety Consulting": ["health and safety", "osha", "risk assessment", "protective equipment"],
    "Food Safety Services": ["food safety", "haccp", "sanitation", "food standards"],
    "Quality Assurance Services": ["quality assurance", "qa", "compliance", "iso", "testing"],
    "Compliance Services": ["compliance", "regulations", "audit", "policies", "governance"],
    "Environmental Health Services": ["environmental health", "toxins", "air quality", "contaminants"],
    "Risk Assessment Services": ["risk assessment", "risk analysis", "hazard", "exposure", "risk mgmt"],
    "Crisis Management Services": ["crisis mgmt", "emergency response", "disaster recovery"],
    "Community Engagement Services": ["community engagement", "public outreach", "stakeholder involvement"],
    "Stakeholder Services": ["stakeholder mgmt", "shareholder", "interest groups", "public relations"],
    "Corporate Responsibility Services": ["csr", "corporate social responsibility", "sustainability", "ethics"],
    "Fundraising Services": ["fundraising", "donations", "charity", "money raising"],
    "Volunteer Services": ["volunteer mgmt", "volunteer coordination", "charity", "ngo help"],
    "Non-Profit Management": ["non-profit mgmt", "foundation", "ngo", "donations", "charity"],
    "Arts Services": ["arts", "theater", "exhibitions", "museums", "performances"],
    "Sports Management Services": ["sports mgmt", "teams", "leagues", "tournaments"],
    "Fitness Coaching": ["fitness", "gym", "exercise", "workout", "personal trainer"],
    "Health Promotion Services": ["health promotion", "wellness", "public health", "prevention"],
    "Physical Therapy Services": ["physical therapy", "rehabilitation", "physiotherapy", "clinic"],
    "Occupational Health Services": ["occupational health", "workplace safety", "ergonomics"]
}